### ISSUE TITLE
Explanation of peptide registers

### ISSUE THREAD

**Issue by mohmhm1** [v-mikhaylov/tfold-release#6]
Hello, 

I ran the example csv and it ran to completion but im having trouble understanding the output of best model file. 

af_tails as i understand it are the starting and ending indices of the peptide segment that is predicted to bind within the MHC groove but for the examples the af tails are 

(0,0) and (4,2)

how does one interpret these results?

Many thanks

**Comment by v-mikhaylov** [comment]
Hi! These two integers are lengths of the left and right flanking regions, i.e. segments of the peptide that are hanging outside of the binding groove -- see fig. 1B in the paper. For class I, it will usually be (0,0) because the register is usually canonical. For class II, these two numbers plus 9 (core length) should sum to the peptide length
